version: '3.8'

services:
  web:
    container_name: portfolio-v3
    image: nginx:latest
    restart: unless-stopped
    ports: []
      # - "1234:80" # HTTP
    volumes:
      - ./html:/usr/share/nginx/html:ro
    networks:
      - home_network

networks:
  home_network:
    external: true
